name: Hello World!

on:
  push:
    branches:
      - master
      
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!" 
      - name: Now it is (11.4)
        run: |
          date  
      - name: Directory content (11.4)
        run: |
          ls -l  